/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.AirlinerDirectory;
import Business.CustomerDirectory;
import Interface.Airliners.LoginAirliner;
import Interface.Customer.CustomerSpecification;
import Interface.TravelAgency.ManageAirliner;
import java.awt.CardLayout;

/**
 *
 * @author sharw
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private AirlinerDirectory airDuct;
    private CustomerDirectory custDict;
    public MainFrame() {
        initComponents();
        airDuct = new AirlinerDirectory();
        custDict=new CustomerDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        leftpane = new javax.swing.JPanel();
        travelbtn = new javax.swing.JButton();
        airlinerbtn = new javax.swing.JButton();
        customerbtn = new javax.swing.JButton();
        rightpane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftpane.setBackground(new java.awt.Color(153, 153, 255));
        leftpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        travelbtn.setBackground(new java.awt.Color(255, 255, 255));
        travelbtn.setFont(new java.awt.Font("SansSerif", 1, 39)); // NOI18N
        travelbtn.setText("Travel Agency");
        travelbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 204)));
        travelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travelbtnActionPerformed(evt);
            }
        });
        leftpane.add(travelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 290, 120));

        airlinerbtn.setBackground(new java.awt.Color(255, 255, 255));
        airlinerbtn.setFont(new java.awt.Font("SansSerif", 1, 39)); // NOI18N
        airlinerbtn.setText("Airliner");
        airlinerbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 204)));
        airlinerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlinerbtnActionPerformed(evt);
            }
        });
        leftpane.add(airlinerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 290, 120));

        customerbtn.setBackground(new java.awt.Color(255, 255, 255));
        customerbtn.setFont(new java.awt.Font("SansSerif", 1, 39)); // NOI18N
        customerbtn.setText("Customer");
        customerbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 204)));
        customerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerbtnActionPerformed(evt);
            }
        });
        leftpane.add(customerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 290, 110));

        jSplitPane1.setLeftComponent(leftpane);

        rightpane.setBackground(new java.awt.Color(255, 255, 255));
        rightpane.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(rightpane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1796, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1093, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void travelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travelbtnActionPerformed
        // TODO add your handling code here:
        
        
        ManageAirliner ma = new ManageAirliner(rightpane,airDuct,custDict);
        rightpane.add("ManageAirliner",ma);
         CardLayout layout = (CardLayout)rightpane.getLayout();
        layout.next(rightpane);
    }//GEN-LAST:event_travelbtnActionPerformed

    private void airlinerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlinerbtnActionPerformed
        // TODO add your handling code here:
        
        LoginAirliner la = new LoginAirliner(rightpane,airDuct);
        rightpane.add("LoginAirliner",la);
         CardLayout layout = (CardLayout)rightpane.getLayout();
        layout.next(rightpane);
    }//GEN-LAST:event_airlinerbtnActionPerformed

    private void customerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerbtnActionPerformed
        // TODO add your handling code here:
        
        CustomerSpecification cs= new CustomerSpecification(rightpane,airDuct,custDict);
        rightpane.add("CustomerSpecification",cs);
         CardLayout layout = (CardLayout)rightpane.getLayout();
        layout.next(rightpane);
    }//GEN-LAST:event_customerbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton airlinerbtn;
    private javax.swing.JButton customerbtn;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel leftpane;
    private javax.swing.JPanel rightpane;
    private javax.swing.JButton travelbtn;
    // End of variables declaration//GEN-END:variables
}
