/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import Business.Customer;
import Business.CustomerDirectory;
import Business.Flightdetails;
import com.sun.glass.events.KeyEvent;
import java.awt.CardLayout;
import java.awt.Font;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sharw
 */
public class flightfilterdata extends javax.swing.JPanel {

    /**
     * Creates new form flightfilterdata
     */
   
JPanel rightpane;
ArrayList<Flightdetails> customerSearch;
 private CustomerDirectory custDict;
 String p;
    flightfilterdata(JPanel rightpane, ArrayList<Flightdetails> customerSearch,CustomerDirectory custDict) {
        initComponents();
        this.rightpane=rightpane;
        this.customerSearch=customerSearch;
        this.custDict=custDict;
        populate10();
        
        
        custflighttbl.getTableHeader().setFont(new Font("SansSerif",Font.BOLD,34));
      
    }
    
    public void populate10(){
    
        int rowCount = custflighttbl.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)custflighttbl.getModel();
        dtm.setRowCount(0);
        
        
        for(Flightdetails fdd : customerSearch){
        Object[] row = new Object[dtm.getColumnCount()];
        row[0]=fdd;
        row[1]=fdd.getSource();
        row[2]=fdd.getDestination();
        row[3]=fdd.getDate();
        row[4]=fdd.getPrice();
        row[5]=fdd.getSeats();
        dtm.addRow(row);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        custflighttbl = new javax.swing.JTable();
        backbtn = new javax.swing.JButton();
        bookbtn = new javax.swing.JButton();
        phonetxt = new javax.swing.JTextField();
        confirmbookingbtn = new javax.swing.JButton();
        passportlbl = new javax.swing.JLabel();
        passporttxt = new javax.swing.JTextField();
        namelbl = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        phonelbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        custflighttbl.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        custflighttbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Number", "Source", "Destination", "Date", "Price", "Seats"
            }
        ));
        jScrollPane1.setViewportView(custflighttbl);

        backbtn.setFont(new java.awt.Font("SansSerif", 1, 34)); // NOI18N
        backbtn.setText("<<Back");
        backbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        bookbtn.setFont(new java.awt.Font("SansSerif", 1, 34)); // NOI18N
        bookbtn.setText("Book ");
        bookbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));
        bookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookbtnActionPerformed(evt);
            }
        });

        phonetxt.setEditable(false);
        phonetxt.setFont(new java.awt.Font("SansSerif", 0, 34)); // NOI18N
        phonetxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));
        phonetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phonetxtKeyPressed(evt);
            }
        });

        confirmbookingbtn.setFont(new java.awt.Font("SansSerif", 1, 34)); // NOI18N
        confirmbookingbtn.setText("Confirm Booking");
        confirmbookingbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));
        confirmbookingbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmbookingbtnActionPerformed(evt);
            }
        });

        passportlbl.setFont(new java.awt.Font("SansSerif", 1, 34)); // NOI18N
        passportlbl.setText("Passport No.:");

        passporttxt.setEditable(false);
        passporttxt.setFont(new java.awt.Font("SansSerif", 0, 34)); // NOI18N
        passporttxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        namelbl.setFont(new java.awt.Font("SansSerif", 1, 34)); // NOI18N
        namelbl.setText("Name:");

        nametxt.setEditable(false);
        nametxt.setFont(new java.awt.Font("SansSerif", 0, 34)); // NOI18N
        nametxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        phonelbl.setFont(new java.awt.Font("SansSerif", 1, 34)); // NOI18N
        phonelbl.setText("Phone No.:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1630, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(73, 73, 73))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(passportlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(passporttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(phonelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(phonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(477, 477, 477))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bookbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(confirmbookingbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(385, 385, 385))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nametxt, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(namelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phonetxt, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(phonelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passportlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passporttxt, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(confirmbookingbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(bookbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(152, 152, 152))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookbtnActionPerformed
        // TODO add your handling code here:
        
        nametxt.setEditable(true);
        phonetxt.setEditable(true);
        passporttxt.setEditable(true);
        //custflighttxt.setEditable(true);
        
        JOptionPane.showMessageDialog(null,"Please select book to add details");
        
    }//GEN-LAST:event_bookbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        customerSearch.clear();
        rightpane.remove(this);//points to the current object
        CardLayout layout = (CardLayout) rightpane.getLayout();
        layout.previous(rightpane);
    }//GEN-LAST:event_backbtnActionPerformed

    private void confirmbookingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmbookingbtnActionPerformed
        // TODO add your handling code here:

        // int value=fd.getSeats();
        if(nametxt.getText().isEmpty()|| phonetxt.getText().isEmpty()|| passporttxt.getText().isEmpty()){
             JOptionPane.showMessageDialog(null,"Please Enter all the fields");
        }
        else{
        int selectedrow=custflighttbl.getSelectedRow();
        String name=nametxt.getText().trim();
        
        String phoneno=phonetxt.getText().trim();
        
        String passport=passporttxt.getText().trim();
        //String custflight=custflighttxt.getText().trim();
        Customer c=custDict.addCustomer();
        c.setName(name);
        c.setPhoneno(phoneno);
        c.setPassportno(passport);
        //c.setCustflight(custflight);
        Flightdetails fd=(Flightdetails)custflighttbl.getValueAt(selectedrow, 0);
        int value=0;
        value=fd.getSeats();
        if(value>0)
        {
        value--;
        fd.setSeats(value);
        }
        else{
        JOptionPane.showMessageDialog(null,"Seats not available");
        }
        c.setFlightnumber(fd.getFlightnumber());
        c.setSource(fd.getSource());
        c.setDestination(fd.getDestination());
        c.setPrice(fd.getPrice());
        //c.setDate(fd.getDate());
        
        if(selectedrow>=0 && !name.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Successfully Booked!!");
            populate10();
            
            nametxt.setEditable(false);
        phonetxt.setEditable(false);
        passporttxt.setEditable(false);
        //custflighttxt.setEditable(false);
        
        nametxt.setText("");
        phonetxt.setText("");
        passporttxt.setText("");
        }
        else{
         JOptionPane.showMessageDialog(null,"Cannot Book. Select flight first.");
        }
        }
    }//GEN-LAST:event_confirmbookingbtnActionPerformed

    private void phonetxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonetxtKeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if((key>=evt.VK_0 && key<=evt.VK_9)|| key==KeyEvent.VK_BACKSPACE)
        {
        phonetxt.setEditable(true);
        }
        else{
        phonetxt.setEditable(false);
        }
            
    }//GEN-LAST:event_phonetxtKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton bookbtn;
    private javax.swing.JButton confirmbookingbtn;
    private javax.swing.JTable custflighttbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namelbl;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel passportlbl;
    private javax.swing.JTextField passporttxt;
    private javax.swing.JLabel phonelbl;
    private javax.swing.JTextField phonetxt;
    // End of variables declaration//GEN-END:variables
}
