/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSignHistory;
import Business.VitalSigns;
import javax.swing.JOptionPane;


/**
 *
 * @author sharw
 */
public class CreateVitalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateVitalJPanel
     */
    private VitalSignHistory vitalsignhistory;
    CreateVitalJPanel(VitalSignHistory vitalsignhistory) {
         initComponents();
         this.vitalsignhistory= vitalsignhistory;
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        temperature = new javax.swing.JLabel();
        temp = new javax.swing.JTextField();
        bp = new javax.swing.JTextField();
        bloodPressure = new javax.swing.JLabel();
        pulsetxt = new javax.swing.JTextField();
        pulse = new javax.swing.JLabel();
        datetxt = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        createLabel = new javax.swing.JLabel();
        saveCreate = new javax.swing.JButton();

        temperature.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        temperature.setText("Temperature :");

        temp.setFont(new java.awt.Font("SansSerif", 0, 32)); // NOI18N
        temp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempActionPerformed(evt);
            }
        });

        bp.setFont(new java.awt.Font("SansSerif", 0, 32)); // NOI18N
        bp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpActionPerformed(evt);
            }
        });

        bloodPressure.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        bloodPressure.setText("Blood Pressure :");

        pulsetxt.setFont(new java.awt.Font("SansSerif", 0, 32)); // NOI18N
        pulsetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsetxtActionPerformed(evt);
            }
        });

        pulse.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        pulse.setText("Pulse :");

        datetxt.setFont(new java.awt.Font("SansSerif", 0, 32)); // NOI18N
        datetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datetxtActionPerformed(evt);
            }
        });

        date.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        date.setText("Date :");

        createLabel.setFont(new java.awt.Font("SansSerif", 1, 42)); // NOI18N
        createLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createLabel.setText("Create Vital Signs");

        saveCreate.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        saveCreate.setText("Save");
        saveCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(438, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pulse, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(66, 66, 66)
                            .addComponent(pulsetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(66, 66, 66)
                            .addComponent(bp, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(temperature, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(66, 66, 66)
                            .addComponent(temp, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(createLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182)))
                .addGap(344, 344, 344))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(createLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(temp)
                    .addComponent(temperature, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bp)
                    .addComponent(bloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pulsetxt)
                    .addComponent(pulse, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(datetxt)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(saveCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(372, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempActionPerformed

    private void bpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bpActionPerformed

    private void pulsetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pulsetxtActionPerformed

    private void datetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datetxtActionPerformed

    private void saveCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCreateActionPerformed
        // TODO add your handling code here:
        try{
        double temperature = Double.parseDouble(temp.getText());
        double bloodpressure=Double.parseDouble(bp.getText());
        int pul= Integer.parseInt(pulsetxt.getText());
        String date= datetxt.getText();
        VitalSigns v= vitalsignhistory.addVitals();
        v.setBloodPressure(bloodpressure);
        v.setTemperature(temperature);
        v.setPulse(pul);
        v.setDate(date);
        
        
        //JOptionPane.showMessageDialog(null, "VitalSigns Added Successfully");
        
         temp.setText("");
         bp.setText("");
         pulsetxt.setText("");
         datetxt.setText("");
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Please add valid input");
        }                               
    }//GEN-LAST:event_saveCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bloodPressure;
    private javax.swing.JTextField bp;
    private javax.swing.JLabel createLabel;
    private javax.swing.JLabel date;
    private javax.swing.JTextField datetxt;
    private javax.swing.JLabel pulse;
    private javax.swing.JTextField pulsetxt;
    private javax.swing.JButton saveCreate;
    private javax.swing.JTextField temp;
    private javax.swing.JLabel temperature;
    // End of variables declaration//GEN-END:variables
}
