/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSignHistory;
import Business.VitalSigns;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author sharw
 */
public class ViewVitalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewVitalJPanel
     */
   
    private VitalSignHistory vitalsignhistory;
    ViewVitalJPanel(VitalSignHistory vitalsignhistory) {
        initComponents();
        this.vitalsignhistory= vitalsignhistory;
        populateTable();
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void populateTable()//display all records in the arraylist
    {
    DefaultTableModel  dtm = (DefaultTableModel)tblVitalSign.getModel();
    dtm.setRowCount(0);
    
    for(VitalSigns vs : vitalsignhistory.getVitalSignHistory())
    {
        Object row[]= new Object[2];
        row[0]=vs;
        row[1]=vs.getBloodPressure();
        dtm.addRow(row);
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewlabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVitalSign = new javax.swing.JTable();
        viewDetails = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        temp = new javax.swing.JTextField();
        bp = new javax.swing.JTextField();
        bloodPressure = new javax.swing.JLabel();
        pulsetxt = new javax.swing.JTextField();
        pulse = new javax.swing.JLabel();
        datetxt = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        temperature = new javax.swing.JLabel();

        viewlabel.setFont(new java.awt.Font("SansSerif", 1, 42)); // NOI18N
        viewlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewlabel.setText("View Vital Sign");

        tblVitalSign.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        tblVitalSign.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Blood Pressure"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVitalSign);

        viewDetails.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        viewDetails.setText("View Details");
        viewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        temp.setEditable(false);
        temp.setFont(new java.awt.Font("SansSerif", 0, 32)); // NOI18N
        temp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempActionPerformed(evt);
            }
        });

        bp.setEditable(false);
        bp.setFont(new java.awt.Font("SansSerif", 0, 32)); // NOI18N
        bp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpActionPerformed(evt);
            }
        });

        bloodPressure.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        bloodPressure.setText("Blood Pressure :");

        pulsetxt.setEditable(false);
        pulsetxt.setFont(new java.awt.Font("SansSerif", 0, 32)); // NOI18N
        pulsetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsetxtActionPerformed(evt);
            }
        });

        pulse.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        pulse.setText("Pulse :");

        datetxt.setEditable(false);
        datetxt.setFont(new java.awt.Font("SansSerif", 0, 32)); // NOI18N
        datetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datetxtActionPerformed(evt);
            }
        });

        date.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        date.setText("Date :");

        temperature.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        temperature.setText("Temperature :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(507, 507, 507)
                        .addComponent(viewlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(temperature, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(798, 798, 798))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pulse, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66)
                                        .addComponent(pulsetxt))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66)
                                        .addComponent(bp, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(106, 106, 106))
                            .addComponent(date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(temp, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(476, 476, 476)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(viewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(670, 670, 670)
                        .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(417, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(viewlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(temp)
                    .addComponent(temperature, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bp)
                    .addComponent(bloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pulsetxt)
                    .addComponent(pulse, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(datetxt)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempActionPerformed

    private void bpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bpActionPerformed

    private void pulsetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pulsetxtActionPerformed

    private void datetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datetxtActionPerformed

    private void viewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsActionPerformed
        // TODO add your handling code here:
        
        int selectedrow = tblVitalSign.getSelectedRow();
        
        if(selectedrow >=0)
        {
            VitalSigns vs= (VitalSigns)tblVitalSign.getValueAt(selectedrow, 0);
            bp.setText(String.valueOf(vs.getBloodPressure()));
            temp.setText(String.valueOf(vs.getTemperature()));
            pulsetxt.setText(String.valueOf(vs.getPulse()));
            datetxt.setText(vs.getDate());
        }
        else
            JOptionPane.showMessageDialog(null, "Please select a row");
    }//GEN-LAST:event_viewDetailsActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
         int selectedrow = tblVitalSign.getSelectedRow();
        
        if(selectedrow >=0)
        {
         VitalSigns vs= (VitalSigns)tblVitalSign.getValueAt(selectedrow, 0);
         vitalsignhistory.deleteVitals(vs);
         JOptionPane.showMessageDialog(null, "Vital sign has been deleted");
         populateTable();
        }
        else
           JOptionPane.showMessageDialog(null, "Please select a row");  
    }//GEN-LAST:event_deleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bloodPressure;
    private javax.swing.JTextField bp;
    private javax.swing.JLabel date;
    private javax.swing.JTextField datetxt;
    private javax.swing.JButton delete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pulse;
    private javax.swing.JTextField pulsetxt;
    private javax.swing.JTable tblVitalSign;
    private javax.swing.JTextField temp;
    private javax.swing.JLabel temperature;
    private javax.swing.JButton viewDetails;
    private javax.swing.JLabel viewlabel;
    // End of variables declaration//GEN-END:variables
}
