/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.TravelAgency;

import Business.AirlinerDirectory;
import Business.CustomerDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sharw
 */
public class ManageAirliner extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirliner
     */
    JPanel rightpane;
    private AirlinerDirectory airDict;
    private CustomerDirectory custDict;
    public ManageAirliner(JPanel rp, AirlinerDirectory ad,CustomerDirectory custDict) {
         initComponents();
         this.rightpane=rp;
         this.airDict=ad;
         this.custDict=custDict;
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageairlinerbtn = new javax.swing.JButton();
        custdetails = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        manageairlinerbtn.setBackground(new java.awt.Color(255, 255, 255));
        manageairlinerbtn.setFont(new java.awt.Font("SansSerif", 1, 39)); // NOI18N
        manageairlinerbtn.setText("Manage Airliner >>");
        manageairlinerbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));
        manageairlinerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageairlinerbtnActionPerformed(evt);
            }
        });

        custdetails.setBackground(new java.awt.Color(255, 255, 255));
        custdetails.setFont(new java.awt.Font("SansSerif", 1, 39)); // NOI18N
        custdetails.setText("View Customer>>");
        custdetails.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));
        custdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custdetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(393, 393, 393)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(custdetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageairlinerbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE))
                .addContainerGap(545, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(406, 406, 406)
                .addComponent(manageairlinerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(custdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(385, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageairlinerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageairlinerbtnActionPerformed
        // TODO add your handling code here:
        AirlinerWorkArea awa = new AirlinerWorkArea(rightpane, airDict);
        rightpane.add("AirlinerWorkArea", awa);
        CardLayout layout = (CardLayout)rightpane.getLayout();
        layout.next(rightpane);
    }//GEN-LAST:event_manageairlinerbtnActionPerformed

    private void custdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custdetailsActionPerformed
        // TODO add your handling code here:
        customerdetailsJPanel cdp = new customerdetailsJPanel(rightpane,custDict);
        rightpane.add("customerdetailsJPanel",cdp);
        CardLayout layout=(CardLayout) rightpane.getLayout();
        layout.next(rightpane);
    }//GEN-LAST:event_custdetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton custdetails;
    private javax.swing.JButton manageairlinerbtn;
    // End of variables declaration//GEN-END:variables
}
