/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.TravelAgency;

import Business.Airliner;
import Business.Flightdetails;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sharw
 */
public class viewairlinerdetails extends javax.swing.JPanel {

    /**
     * Creates new form viewairlinerdetails
     */
    private JPanel rightpane;
    private Airliner a;
    public viewairlinerdetails(JPanel rightpane, Airliner a) {
        initComponents();
        this.rightpane=rightpane;
        this.a=a;
        
        airlinername.setText(a.getaName());
        populate12();
    }

    public void populate12() {
        int rowCount = airlinerdetailstbl.getRowCount();
        DefaultTableModel model = (DefaultTableModel)airlinerdetailstbl.getModel();
        model.setRowCount(0);
        //for(int i=rowCount-1;i>=0;i--) {
          //  model.removeRow(i);
        //}
    
        
        for(Flightdetails fd : a.getFlightDetailsDict().getFlightDetailsDict()) {
            Object row[] = new Object[model.getColumnCount()];
            row[0] = fd;
            row[1] = fd.getSource();
            row[2] = fd.getDestination();
            row[3] = fd.getSeats();
            row[4] = fd.getDate();
            row[5] = fd.getPrice();
            model.addRow(row);
            }
        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        airlinerdetailstbl = new javax.swing.JTable();
        airlinernamelbl = new javax.swing.JLabel();
        airlinername = new javax.swing.JTextField();
        airlinerheading = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        airlinerdetailstbl.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        airlinerdetailstbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Name", "Source", "Destination", "Seats", "Price", "Date"
            }
        ));
        jScrollPane1.setViewportView(airlinerdetailstbl);

        airlinernamelbl.setText("Airliner Name:");

        airlinername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlinernameActionPerformed(evt);
            }
        });

        airlinerheading.setFont(new java.awt.Font("SansSerif", 1, 39)); // NOI18N
        airlinerheading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        airlinerheading.setText("Airliner Details");

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 34)); // NOI18N
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(airlinerheading, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(471, 471, 471))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(airlinernamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(airlinername, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(airlinerheading, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(226, 226, 226)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airlinername, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(airlinernamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(341, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void airlinernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlinernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airlinernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        rightpane.remove(this);
         CardLayout layout = (CardLayout)rightpane.getLayout();
        layout.previous(rightpane);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable airlinerdetailstbl;
    private javax.swing.JLabel airlinerheading;
    private javax.swing.JTextField airlinername;
    private javax.swing.JLabel airlinernamelbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
