/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.AddressInfo;
//import Business.Personal;
import javax.swing.JOptionPane;
/**
 *
 * @author sharw
 */
public class Address extends javax.swing.JPanel {

    /**
     * Creates new form Address
     */
    private AddressInfo address;
    public Address(AddressInfo address) {
        initComponents();
        this.address=address;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddressHeading = new javax.swing.JLabel();
        streetAdd = new javax.swing.JLabel();
        StreetAdd = new javax.swing.JTextField();
        city = new javax.swing.JLabel();
        City = new javax.swing.JTextField();
        state = new javax.swing.JLabel();
        State = new javax.swing.JTextField();
        zipcode = new javax.swing.JLabel();
        ZipCode = new javax.swing.JTextField();
        insertAdd = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        AddressHeading.setFont(new java.awt.Font("SansSerif", 1, 45)); // NOI18N
        AddressHeading.setForeground(new java.awt.Color(0, 51, 153));
        AddressHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddressHeading.setText("Insert  Address Information");

        streetAdd.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        streetAdd.setForeground(new java.awt.Color(0, 51, 153));
        streetAdd.setText("Street Address :");

        StreetAdd.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        StreetAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        city.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        city.setForeground(new java.awt.Color(0, 51, 153));
        city.setText("City :");

        City.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        City.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        state.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        state.setForeground(new java.awt.Color(0, 51, 153));
        state.setText("State :");

        State.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        State.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        zipcode.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        zipcode.setForeground(new java.awt.Color(0, 51, 153));
        zipcode.setText("Zip Code :");

        ZipCode.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        ZipCode.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));
        ZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZipCodeActionPerformed(evt);
            }
        });

        insertAdd.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        insertAdd.setForeground(new java.awt.Color(0, 51, 153));
        insertAdd.setText("Insert");
        insertAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(streetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(State, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
                    .addComponent(City, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StreetAdd, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ZipCode))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(508, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(insertAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(811, 811, 811))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AddressHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(460, 460, 460))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(AddressHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(streetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StreetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(City)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(insertAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(382, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZipCodeActionPerformed

    private void insertAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertAddActionPerformed
        // TODO add your handling code here:
        address.setStreetadd(StreetAdd.getText());
        address.setCity(City.getText());
        address.setState(State.getText());
        address.setZipcode(ZipCode.getText());
        
         if(StreetAdd.getText().isEmpty() || City.getText().isEmpty() || State.getText().isEmpty() || ZipCode.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter data into all the required fields");
        }
         else{
        JOptionPane.showMessageDialog(null,"Successfully Inserted");
    }//GEN-LAST:event_insertAddActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressHeading;
    private javax.swing.JTextField City;
    private javax.swing.JTextField State;
    private javax.swing.JTextField StreetAdd;
    private javax.swing.JTextField ZipCode;
    private javax.swing.JLabel city;
    private javax.swing.JButton insertAdd;
    private javax.swing.JLabel state;
    private javax.swing.JLabel streetAdd;
    private javax.swing.JLabel zipcode;
    // End of variables declaration//GEN-END:variables
}
