/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Personal;
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;
/**
 *
 * @author sharw
 */
public class DemoPanel extends javax.swing.JPanel {

    /**
     * Creates new form DemoPanel
     */
    
        private Personal personal;
        public DemoPanel(Personal personal) {
        initComponents();
        this.personal=personal;
        //getContentPane().setBackground(Color.BEIGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DemoHeading = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        phoneno = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        height = new javax.swing.JLabel();
        weight = new javax.swing.JLabel();
        ssn = new javax.swing.JLabel();
        Fname = new javax.swing.JTextField();
        Lname = new javax.swing.JTextField();
        Phoneno = new javax.swing.JTextField();
        DoB = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        Htg = new javax.swing.JTextField();
        Wtg = new javax.swing.JTextField();
        SSN = new javax.swing.JTextField();
        insertDemo = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        DemoHeading.setFont(new java.awt.Font("SansSerif", 1, 45)); // NOI18N
        DemoHeading.setForeground(new java.awt.Color(0, 51, 153));
        DemoHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DemoHeading.setText("Insert  Demographic Information");

        fname.setFont(new java.awt.Font("SansSerif", 1, 35)); // NOI18N
        fname.setForeground(new java.awt.Color(0, 51, 153));
        fname.setText("First Name :");

        lname.setFont(new java.awt.Font("SansSerif", 1, 35)); // NOI18N
        lname.setForeground(new java.awt.Color(0, 51, 153));
        lname.setText("Last Name :");

        phoneno.setFont(new java.awt.Font("SansSerif", 1, 35)); // NOI18N
        phoneno.setForeground(new java.awt.Color(0, 51, 153));
        phoneno.setText("Phone Number:");

        dob.setFont(new java.awt.Font("SansSerif", 1, 35)); // NOI18N
        dob.setForeground(new java.awt.Color(0, 51, 153));
        dob.setText("Date Of Birth :");

        age.setFont(new java.awt.Font("SansSerif", 1, 35)); // NOI18N
        age.setForeground(new java.awt.Color(0, 51, 153));
        age.setText("Age :");

        height.setFont(new java.awt.Font("SansSerif", 1, 35)); // NOI18N
        height.setForeground(new java.awt.Color(0, 51, 153));
        height.setText("Height :");

        weight.setFont(new java.awt.Font("SansSerif", 1, 35)); // NOI18N
        weight.setForeground(new java.awt.Color(0, 51, 153));
        weight.setText("Weight :");

        ssn.setFont(new java.awt.Font("SansSerif", 1, 35)); // NOI18N
        ssn.setForeground(new java.awt.Color(0, 51, 153));
        ssn.setText("SSN :");

        Fname.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Fname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));
        Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameActionPerformed(evt);
            }
        });

        Lname.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Lname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        Phoneno.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Phoneno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        DoB.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        DoB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));
        DoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoBActionPerformed(evt);
            }
        });

        Age.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Age.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        Htg.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Htg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        Wtg.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Wtg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        SSN.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        SSN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        insertDemo.setFont(new java.awt.Font("SansSerif", 1, 35)); // NOI18N
        insertDemo.setForeground(new java.awt.Color(0, 51, 153));
        insertDemo.setText("Insert");
        insertDemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertDemoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(500, 500, 500)
                        .addComponent(DemoHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lname, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
                            .addComponent(Phoneno)
                            .addComponent(DoB)
                            .addComponent(Age)
                            .addComponent(Htg)
                            .addComponent(Wtg)
                            .addComponent(SSN)
                            .addComponent(Fname))))
                .addGap(421, 421, 421))
            .addGroup(layout.createSequentialGroup()
                .addGap(781, 781, 781)
                .addComponent(insertDemo, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DemoHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Fname)
                        .addGap(2, 2, 2)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lname)
                    .addComponent(lname, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DoB)
                    .addComponent(dob, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Age)
                    .addComponent(age, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Htg)
                    .addComponent(height, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Wtg)
                    .addComponent(weight, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSN, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(insertDemo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoBActionPerformed

    private void insertDemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertDemoActionPerformed
        // TODO add your handling code here:
        personal.setFname(Fname.getText());
        personal.setLname(Lname.getText());
        personal.setPhoneno(Phoneno.getText());
        personal.setDOB(DoB.getText());
        personal.setAge(Age.getText());
        personal.setHeight(Htg.getText());
        personal.setWeight(Wtg.getText());
        personal.setSSN(SSN.getText());
        
        if(Fname.getText().isEmpty() || Lname.getText().isEmpty() || Phoneno.getText().isEmpty() || DoB.getText().isEmpty() || Age.getText().isEmpty() || Htg.getText().isEmpty() || Wtg.getText().isEmpty() || SSN.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter data into all the required fields");
        }
        else{
        JOptionPane.showMessageDialog(null,"Successfully Inserted");
    }//GEN-LAST:event_insertDemoActionPerformed
    }
    private void FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JLabel DemoHeading;
    private javax.swing.JTextField DoB;
    private javax.swing.JTextField Fname;
    private javax.swing.JTextField Htg;
    private javax.swing.JTextField Lname;
    private javax.swing.JTextField Phoneno;
    private javax.swing.JTextField SSN;
    private javax.swing.JTextField Wtg;
    private javax.swing.JLabel age;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel fname;
    private javax.swing.JLabel height;
    private javax.swing.JButton insertDemo;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel phoneno;
    private javax.swing.JLabel ssn;
    private javax.swing.JLabel weight;
    // End of variables declaration//GEN-END:variables
}
