/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.License;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author sharw
 */


public class LicenseInformation extends javax.swing.JPanel {

    /**
     * Creates new form LicenseInformation
     */
    private License l;
    public LicenseInformation(License l) {
        initComponents();
        this.l=l;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        licenseheading = new javax.swing.JLabel();
        lno = new javax.swing.JLabel();
        issuedate = new javax.swing.JLabel();
        expdate = new javax.swing.JLabel();
        bloodtype = new javax.swing.JLabel();
        bt = new javax.swing.JTextField();
        ed = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        licenseno = new javax.swing.JTextField();
        insertLicense = new javax.swing.JButton();
        picture = new javax.swing.JLabel();
        picturetxtfield = new javax.swing.JTextField();
        attachbtn = new javax.swing.JButton();

        licenseheading.setFont(new java.awt.Font("SansSerif", 1, 45)); // NOI18N
        licenseheading.setForeground(new java.awt.Color(0, 51, 153));
        licenseheading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        licenseheading.setText("Insert  Driver's License Information");

        lno.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lno.setForeground(new java.awt.Color(0, 51, 153));
        lno.setText("License Number :");

        issuedate.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        issuedate.setForeground(new java.awt.Color(0, 51, 153));
        issuedate.setText("Issue Date:");

        expdate.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        expdate.setForeground(new java.awt.Color(0, 51, 153));
        expdate.setText("Expiry Date :");

        bloodtype.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        bloodtype.setForeground(new java.awt.Color(0, 51, 153));
        bloodtype.setText("Blood Type :");

        bt.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        bt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        ed.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        ed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        id.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        id.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        licenseno.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        licenseno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        insertLicense.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        insertLicense.setForeground(new java.awt.Color(0, 51, 153));
        insertLicense.setText("Insert");
        insertLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertLicenseActionPerformed(evt);
            }
        });

        picture.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        picture.setForeground(new java.awt.Color(0, 51, 153));
        picture.setText("Picture :");

        picturetxtfield.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        picturetxtfield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        attachbtn.setText("Attach");
        attachbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(363, Short.MAX_VALUE)
                .addComponent(licenseheading, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(460, 460, 460))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(issuedate, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lno, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expdate, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloodtype, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attachbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
                        .addComponent(id, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(licenseno, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(insertLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(picturetxtfield, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(licenseheading, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lno, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licenseno, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(id)
                    .addComponent(issuedate, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(expdate, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ed, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodtype, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(picturetxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(insertLicense, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(attachbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(252, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void insertLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertLicenseActionPerformed
        // TODO add your handling code here:
        l.setLno(licenseno.getText());
        l.setId(id.getText());
        l.setEd(ed.getText());
        l.setBt(bt.getText());
        l.setPicturetxtfield(picturetxtfield.getText());

        if(licenseno.getText().isEmpty() || id.getText().isEmpty() || ed.getText().isEmpty() || bt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter data into all the required fields");
        }
        else{
            JOptionPane.showMessageDialog(null,"Successfully Inserted");
    }//GEN-LAST:event_insertLicenseActionPerformed

    }
    private void attachbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachbtnActionPerformed
        // TODO add your handling code here:
        JFileChooser ch= new JFileChooser();
        FileNameExtensionFilter FNEF = new FileNameExtensionFilter("JPG & GIF Images", "jpg","gif");
        ch.setFileFilter(FNEF);
        ch.showOpenDialog(null);
        File file=ch.getSelectedFile();
        String pathname=file.getAbsolutePath();
        picturetxtfield.setText(pathname);
        
    }//GEN-LAST:event_attachbtnActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attachbtn;
    private javax.swing.JLabel bloodtype;
    private javax.swing.JTextField bt;
    private javax.swing.JTextField ed;
    private javax.swing.JLabel expdate;
    private javax.swing.JTextField id;
    private javax.swing.JButton insertLicense;
    private javax.swing.JLabel issuedate;
    private javax.swing.JLabel licenseheading;
    private javax.swing.JTextField licenseno;
    private javax.swing.JLabel lno;
    private javax.swing.JLabel picture;
    private javax.swing.JTextField picturetxtfield;
    // End of variables declaration//GEN-END:variables
}
