/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Personal;
import java.awt.Color;
//import Business.AddressInfo;
/**
 *
 * @author sharw
 */
public class MainJframe extends javax.swing.JFrame {

    /**
     * Creates new form MainJframe
     */
    private Personal personal;
     
    public MainJframe() {
        initComponents();
        personal =new Personal();
        //getContentPane().setBackground(Color.BLACK);
     // getContentPane().setBackground(Color.BLACK); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPanel = new javax.swing.JSplitPane();
        controljPanel = new javax.swing.JPanel();
        insertDemo = new javax.swing.JButton();
        insertAdd = new javax.swing.JButton();
        insertSavings = new javax.swing.JButton();
        insertChecking = new javax.swing.JButton();
        insertLicense = new javax.swing.JButton();
        insertMedical = new javax.swing.JButton();
        view = new javax.swing.JButton();
        displayjPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controljPanel.setBackground(new java.awt.Color(153, 153, 255));

        insertDemo.setBackground(new java.awt.Color(255, 255, 255));
        insertDemo.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        insertDemo.setForeground(new java.awt.Color(0, 51, 153));
        insertDemo.setText("Insert Demographic Info");
        insertDemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertDemoActionPerformed(evt);
            }
        });

        insertAdd.setBackground(new java.awt.Color(255, 255, 255));
        insertAdd.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        insertAdd.setForeground(new java.awt.Color(0, 51, 153));
        insertAdd.setText("Insert Address Info");
        insertAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertAddActionPerformed(evt);
            }
        });

        insertSavings.setBackground(new java.awt.Color(255, 255, 255));
        insertSavings.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        insertSavings.setForeground(new java.awt.Color(0, 51, 153));
        insertSavings.setText("Insert Savings Info");
        insertSavings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertSavingsActionPerformed(evt);
            }
        });

        insertChecking.setBackground(new java.awt.Color(255, 255, 255));
        insertChecking.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        insertChecking.setForeground(new java.awt.Color(0, 51, 153));
        insertChecking.setText("Insert Checking Info");
        insertChecking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertCheckingActionPerformed(evt);
            }
        });

        insertLicense.setBackground(new java.awt.Color(255, 255, 255));
        insertLicense.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        insertLicense.setForeground(new java.awt.Color(0, 51, 153));
        insertLicense.setText("Insert Licence Info");
        insertLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertLicenseActionPerformed(evt);
            }
        });

        insertMedical.setBackground(new java.awt.Color(255, 255, 255));
        insertMedical.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        insertMedical.setForeground(new java.awt.Color(0, 51, 153));
        insertMedical.setText("Insert Medical Record");
        insertMedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertMedicalActionPerformed(evt);
            }
        });

        view.setBackground(new java.awt.Color(255, 255, 255));
        view.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        view.setForeground(new java.awt.Color(0, 51, 153));
        view.setText("View All");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controljPanelLayout = new javax.swing.GroupLayout(controljPanel);
        controljPanel.setLayout(controljPanelLayout);
        controljPanelLayout.setHorizontalGroup(
            controljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controljPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(controljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(insertDemo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertSavings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertChecking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertLicense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertMedical, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controljPanelLayout.setVerticalGroup(
            controljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controljPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(insertDemo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(insertAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(insertSavings, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(insertChecking, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(insertLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(insertMedical, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(410, Short.MAX_VALUE))
        );

        splitPanel.setLeftComponent(controljPanel);

        displayjPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout displayjPanelLayout = new javax.swing.GroupLayout(displayjPanel);
        displayjPanel.setLayout(displayjPanelLayout);
        displayjPanelLayout.setHorizontalGroup(
            displayjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1949, Short.MAX_VALUE)
        );
        displayjPanelLayout.setVerticalGroup(
            displayjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1347, Short.MAX_VALUE)
        );

        splitPanel.setRightComponent(displayjPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertDemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertDemoActionPerformed
        // TODO add your handling code here:
        DemoPanel demo=new DemoPanel(personal);
        splitPanel.setRightComponent(demo);
        
    }//GEN-LAST:event_insertDemoActionPerformed

    private void insertAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertAddActionPerformed
        // TODO add your handling code here:
        Address addr=new Address(personal.getAddress());
        splitPanel.setRightComponent(addr);
    }//GEN-LAST:event_insertAddActionPerformed

    private void insertSavingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertSavingsActionPerformed
        // TODO add your handling code here:
        Savingsinfo savings=new Savingsinfo(personal.getSaving());
       splitPanel.setRightComponent(savings);
    }//GEN-LAST:event_insertSavingsActionPerformed

    private void insertCheckingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertCheckingActionPerformed
        // TODO add your handling code here:
        Checkingsinfo checking=new Checkingsinfo(personal.getChecking());
        splitPanel.setRightComponent(checking);
    }//GEN-LAST:event_insertCheckingActionPerformed

    private void insertLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertLicenseActionPerformed
        // TODO add your handling code here:
        LicenseInformation license=new LicenseInformation(personal.getLicense());
         splitPanel.setRightComponent(license);
    }//GEN-LAST:event_insertLicenseActionPerformed

    private void insertMedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertMedicalActionPerformed
        // TODO add your handling code here:
        
        Medicalinfo med=new Medicalinfo(personal.getMedical());
        splitPanel.setRightComponent(med);
    }//GEN-LAST:event_insertMedicalActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
        
        View view=new View(personal);
        splitPanel.setRightComponent(view);
        
        
    }//GEN-LAST:event_viewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controljPanel;
    private javax.swing.JPanel displayjPanel;
    private javax.swing.JButton insertAdd;
    private javax.swing.JButton insertChecking;
    private javax.swing.JButton insertDemo;
    private javax.swing.JButton insertLicense;
    private javax.swing.JButton insertMedical;
    private javax.swing.JButton insertSavings;
    private javax.swing.JSplitPane splitPanel;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
