/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Medical;
import javax.swing.JOptionPane;

/**
 *
 * @author sharw
 */
public class Medicalinfo extends javax.swing.JPanel {

    /**
     * Creates new form Medicalinfo
     */
    private Medical medical;
    public Medicalinfo(Medical medical) {
        initComponents();
        this.medical=medical;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MedicalHeading = new javax.swing.JLabel();
        recordno = new javax.swing.JLabel();
        alergy1 = new javax.swing.JLabel();
        alergy2 = new javax.swing.JLabel();
        alergy3 = new javax.swing.JLabel();
        Alergy3 = new javax.swing.JTextField();
        Alergy2 = new javax.swing.JTextField();
        Alergy1 = new javax.swing.JTextField();
        RecordNo = new javax.swing.JTextField();
        insertmedical = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        MedicalHeading.setFont(new java.awt.Font("SansSerif", 1, 45)); // NOI18N
        MedicalHeading.setForeground(new java.awt.Color(0, 51, 153));
        MedicalHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MedicalHeading.setText("Insert Medical Record Information");

        recordno.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        recordno.setForeground(new java.awt.Color(0, 51, 153));
        recordno.setText("Record Number :");

        alergy1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        alergy1.setForeground(new java.awt.Color(0, 51, 153));
        alergy1.setText("Alergy 1 :");

        alergy2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        alergy2.setForeground(new java.awt.Color(0, 51, 153));
        alergy2.setText("Alergy 2 :");

        alergy3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        alergy3.setForeground(new java.awt.Color(0, 51, 153));
        alergy3.setText("Alergy 3 :");

        Alergy3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Alergy3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));
        Alergy3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alergy3ActionPerformed(evt);
            }
        });

        Alergy2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Alergy2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        Alergy1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Alergy1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        RecordNo.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        RecordNo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        insertmedical.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        insertmedical.setForeground(new java.awt.Color(0, 51, 153));
        insertmedical.setText("Insert");
        insertmedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertmedicalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(alergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recordno, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Alergy2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
                    .addComponent(Alergy1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RecordNo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Alergy3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(493, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(MedicalHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(482, 482, 482))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(insertmedical, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(811, 811, 811))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(MedicalHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(recordno, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RecordNo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Alergy1)
                    .addComponent(alergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(alergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Alergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Alergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(insertmedical, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Alergy3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alergy3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Alergy3ActionPerformed

    private void insertmedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertmedicalActionPerformed
        // TODO add your handling code here:
        medical.setMedRecNo(RecordNo.getText());
        medical.setAlergy1(Alergy1.getText());
        medical.setAlergy2(Alergy2.getText());
        medical.setAlergy3(Alergy3.getText());

        
        if(RecordNo.getText().isEmpty() || Alergy1.getText().isEmpty() || Alergy2.getText().isEmpty() || Alergy3.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null,"Please enter data into all the required fields");
        }
        else{
        JOptionPane.showMessageDialog(null,"Successfully Inserted");
    }//GEN-LAST:event_insertmedicalActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alergy1;
    private javax.swing.JTextField Alergy2;
    private javax.swing.JTextField Alergy3;
    private javax.swing.JLabel MedicalHeading;
    private javax.swing.JTextField RecordNo;
    private javax.swing.JLabel alergy1;
    private javax.swing.JLabel alergy2;
    private javax.swing.JLabel alergy3;
    private javax.swing.JButton insertmedical;
    private javax.swing.JLabel recordno;
    // End of variables declaration//GEN-END:variables
}
