/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Personal;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;


/**
 *
 * @author sharw
 */
public class View extends javax.swing.JPanel {

    /**
     * Creates new form View
     */
    
    public View(Personal personal) {
        initComponents();
        
       displayProduct(personal);
       
     
    }

    private void displayProduct(Personal personal){
    
    String personalFName=personal.getFname();
    Fname.setText(personalFName);
    
    String personalLName=personal.getLname();
    Lname.setText(personalLName);
    
    String personalPhoneno=personal.getPhoneno();
    Phoneno.setText(personalPhoneno);
    
    String personalDOB=personal.getDOB();
    DoB.setText(personalDOB);
    
    String personalAge=personal.getAge();
    Age.setText(personalAge);
    
    String personalHeight=personal.getHeight();
    Htg.setText(personalHeight);
    
    String personalWeight=personal.getWeight();
    Wtg.setText(personalWeight);
    
    String personalSSN=personal.getSSN();
    SSN.setText(personalSSN);
    
    String StreetAddress= personal.getAddress().getStreetadd();
    StreetAdd.setText(StreetAddress);
    
    String city=personal.getAddress().getCity();
    City.setText(city);
    
    String state=personal.getAddress().getState();
    State.setText(state);

    String Zipcode=personal.getAddress().getZipcode();
    ZipCode.setText(Zipcode);
    
    String bankname=personal.getSaving().getSBankname();
    BankName.setText(bankname);
    
    String routingno=personal.getSaving().getSRoutingNo();
    RoutingNo.setText(routingno);
    
    String accno=personal.getSaving().getSAccNo();
    AccountNo.setText(accno);
    
    String bal=personal.getSaving().getSBal();
    Balance.setText(bal);
    
    String acctype=personal.getSaving().getSAccType();
    AccountType.setText(acctype);
    
    String bankname1=personal.getChecking().getCBankName();
    BankName1.setText(bankname1);
    
    String routingno1=personal.getChecking().getCRoutingNo();
    RoutingNo1.setText(routingno1);
    
    String accountno1=personal.getChecking().getCAccNo();
    AccountNo1.setText(accountno1);
    
    String bal1=personal.getChecking().getCBal();
    Balance1.setText(bal1);
    
    String lnumber=personal.getLicense().getLno();
    licenseno.setText(lnumber);
    
    String issued=personal.getLicense().getId();
    id.setText(issued);
    
    String expd=personal.getLicense().getEd();
    ed.setText(expd);
    
    String bloodt=personal.getLicense().getBt();
    bt.setText(bloodt);
    
    String imagepath = personal.getLicense().getPicturetxtfield();
    Image pic = Toolkit.getDefaultToolkit().createImage(imagepath);
    pic = pic.getScaledInstance(365, 370, Image.SCALE_SMOOTH);
    ImageIcon ic = new ImageIcon(pic);
    piclabel.setIcon(ic);
    
    String acctype1=personal.getChecking().getCAccType();
    AccountType1.setText(acctype1);
    
    String recno=personal.getMedical().getMedRecNo();
    RecordNo.setText(recno);
    
    String alergy1=personal.getMedical().getAlergy1();
    Alergy1.setText(alergy1);
    
    String alergy2=personal.getMedical().getAlergy2();
    Alergy2.setText(alergy2);
    
    String alergy3=personal.getMedical().getAlergy3();
    Alergy3.setText(alergy3);
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fname = new javax.swing.JTextField();
        Lname = new javax.swing.JTextField();
        Phoneno = new javax.swing.JTextField();
        DoB = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        Htg = new javax.swing.JTextField();
        Wtg = new javax.swing.JTextField();
        SSN = new javax.swing.JTextField();
        DemoHeading = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        phoneno = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        height = new javax.swing.JLabel();
        weight = new javax.swing.JLabel();
        ssn = new javax.swing.JLabel();
        streetAdd = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        state = new javax.swing.JLabel();
        zipcode = new javax.swing.JLabel();
        ZipCode = new javax.swing.JTextField();
        State = new javax.swing.JTextField();
        City = new javax.swing.JTextField();
        StreetAdd = new javax.swing.JTextField();
        bankname = new javax.swing.JLabel();
        BankName = new javax.swing.JTextField();
        RoutingNo = new javax.swing.JTextField();
        routingno = new javax.swing.JLabel();
        accountno = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        accounttype = new javax.swing.JLabel();
        AccountNo = new javax.swing.JTextField();
        Balance = new javax.swing.JTextField();
        AccountType = new javax.swing.JTextField();
        savingslabel = new javax.swing.JLabel();
        savingslabel1 = new javax.swing.JLabel();
        bankname1 = new javax.swing.JLabel();
        routingno1 = new javax.swing.JLabel();
        accountno1 = new javax.swing.JLabel();
        balance1 = new javax.swing.JLabel();
        accounttype1 = new javax.swing.JLabel();
        BankName1 = new javax.swing.JTextField();
        RoutingNo1 = new javax.swing.JTextField();
        AccountNo1 = new javax.swing.JTextField();
        Balance1 = new javax.swing.JTextField();
        AccountType1 = new javax.swing.JTextField();
        medrec = new javax.swing.JLabel();
        lno = new javax.swing.JLabel();
        issuedate = new javax.swing.JLabel();
        expirydate = new javax.swing.JLabel();
        bloodtype = new javax.swing.JLabel();
        licenseno = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        ed = new javax.swing.JTextField();
        bt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        recordno = new javax.swing.JLabel();
        alergy1 = new javax.swing.JLabel();
        alergy2 = new javax.swing.JLabel();
        alergy3 = new javax.swing.JLabel();
        RecordNo = new javax.swing.JTextField();
        Alergy1 = new javax.swing.JTextField();
        Alergy2 = new javax.swing.JTextField();
        Alergy3 = new javax.swing.JTextField();
        piclabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        Fname.setEditable(false);
        Fname.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Fname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));
        Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameActionPerformed(evt);
            }
        });

        Lname.setEditable(false);
        Lname.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Lname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        Phoneno.setEditable(false);
        Phoneno.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Phoneno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        DoB.setEditable(false);
        DoB.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        DoB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));
        DoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoBActionPerformed(evt);
            }
        });

        Age.setEditable(false);
        Age.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Age.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        Htg.setEditable(false);
        Htg.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Htg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        Wtg.setEditable(false);
        Wtg.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Wtg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        SSN.setEditable(false);
        SSN.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        SSN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        DemoHeading.setFont(new java.awt.Font("SansSerif", 1, 45)); // NOI18N
        DemoHeading.setForeground(new java.awt.Color(0, 51, 153));
        DemoHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DemoHeading.setText("Report");

        fname.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        fname.setForeground(new java.awt.Color(0, 51, 153));
        fname.setText("First Name :");

        lname.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        lname.setForeground(new java.awt.Color(0, 51, 153));
        lname.setText("Last Name :");

        phoneno.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        phoneno.setForeground(new java.awt.Color(0, 51, 153));
        phoneno.setText("Phone No. :");

        dob.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        dob.setForeground(new java.awt.Color(0, 51, 153));
        dob.setText("Date Of Birth :");

        age.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        age.setForeground(new java.awt.Color(0, 51, 153));
        age.setText("Age :");

        height.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        height.setForeground(new java.awt.Color(0, 51, 153));
        height.setText("Height :");

        weight.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        weight.setForeground(new java.awt.Color(0, 51, 153));
        weight.setText("Weight :");

        ssn.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        ssn.setForeground(new java.awt.Color(0, 51, 153));
        ssn.setText("SSN :");

        streetAdd.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        streetAdd.setForeground(new java.awt.Color(0, 51, 153));
        streetAdd.setText("Street Address :");

        city.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        city.setForeground(new java.awt.Color(0, 51, 153));
        city.setText("City :");

        state.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        state.setForeground(new java.awt.Color(0, 51, 153));
        state.setText("State :");

        zipcode.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        zipcode.setForeground(new java.awt.Color(0, 51, 153));
        zipcode.setText("Zip Code :");

        ZipCode.setEditable(false);
        ZipCode.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        ZipCode.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));
        ZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZipCodeActionPerformed(evt);
            }
        });

        State.setEditable(false);
        State.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        State.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        City.setEditable(false);
        City.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        City.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));
        City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityActionPerformed(evt);
            }
        });

        StreetAdd.setEditable(false);
        StreetAdd.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        StreetAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));
        StreetAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StreetAddActionPerformed(evt);
            }
        });

        bankname.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        bankname.setForeground(new java.awt.Color(0, 51, 153));
        bankname.setText("Bank Name :");

        BankName.setEditable(false);
        BankName.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        BankName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        RoutingNo.setEditable(false);
        RoutingNo.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        RoutingNo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        routingno.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        routingno.setForeground(new java.awt.Color(0, 51, 153));
        routingno.setText("Routing Number :");

        accountno.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        accountno.setForeground(new java.awt.Color(0, 51, 153));
        accountno.setText("Account Number :");

        balance.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        balance.setForeground(new java.awt.Color(0, 51, 153));
        balance.setText("Account Balance :");

        accounttype.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        accounttype.setForeground(new java.awt.Color(0, 51, 153));
        accounttype.setText("Account Type :");

        AccountNo.setEditable(false);
        AccountNo.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        AccountNo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        Balance.setEditable(false);
        Balance.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Balance.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));
        Balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceActionPerformed(evt);
            }
        });

        AccountType.setEditable(false);
        AccountType.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        AccountType.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));
        AccountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountTypeActionPerformed(evt);
            }
        });

        savingslabel.setFont(new java.awt.Font("Times New Roman", 3, 35)); // NOI18N
        savingslabel.setForeground(new java.awt.Color(0, 51, 153));
        savingslabel.setText("Savings Account Information :");

        savingslabel1.setFont(new java.awt.Font("Times New Roman", 3, 35)); // NOI18N
        savingslabel1.setForeground(new java.awt.Color(0, 51, 153));
        savingslabel1.setText("Checking Account Information :");

        bankname1.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        bankname1.setForeground(new java.awt.Color(0, 51, 153));
        bankname1.setText("Bank Name :");

        routingno1.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        routingno1.setForeground(new java.awt.Color(0, 51, 153));
        routingno1.setText("Routing Number :");

        accountno1.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        accountno1.setForeground(new java.awt.Color(0, 51, 153));
        accountno1.setText("Account Number :");

        balance1.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        balance1.setForeground(new java.awt.Color(0, 51, 153));
        balance1.setText("Account Balance :");

        accounttype1.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        accounttype1.setForeground(new java.awt.Color(0, 51, 153));
        accounttype1.setText("Account Type :");

        BankName1.setEditable(false);
        BankName1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        BankName1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        RoutingNo1.setEditable(false);
        RoutingNo1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        RoutingNo1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        AccountNo1.setEditable(false);
        AccountNo1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        AccountNo1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        Balance1.setEditable(false);
        Balance1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Balance1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));
        Balance1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Balance1ActionPerformed(evt);
            }
        });

        AccountType1.setEditable(false);
        AccountType1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        AccountType1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));
        AccountType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountType1ActionPerformed(evt);
            }
        });

        medrec.setFont(new java.awt.Font("Times New Roman", 3, 35)); // NOI18N
        medrec.setForeground(new java.awt.Color(0, 51, 153));
        medrec.setText("Medical Record Information :");

        lno.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        lno.setForeground(new java.awt.Color(0, 51, 153));
        lno.setText("License Number :");

        issuedate.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        issuedate.setForeground(new java.awt.Color(0, 51, 153));
        issuedate.setText("Issue Date :");

        expirydate.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        expirydate.setForeground(new java.awt.Color(0, 51, 153));
        expirydate.setText("Expiration Date :");

        bloodtype.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        bloodtype.setForeground(new java.awt.Color(0, 51, 153));
        bloodtype.setText("Blood Type :");

        licenseno.setEditable(false);
        licenseno.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N

        id.setEditable(false);
        id.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N

        ed.setEditable(false);
        ed.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N

        bt.setEditable(false);
        bt.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 35)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Driver's License Information :");

        recordno.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        recordno.setForeground(new java.awt.Color(0, 51, 153));
        recordno.setText("Record Number :");

        alergy1.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        alergy1.setForeground(new java.awt.Color(0, 51, 153));
        alergy1.setText("Alergy 1 :");

        alergy2.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        alergy2.setForeground(new java.awt.Color(0, 51, 153));
        alergy2.setText("Alergy 2 :");

        alergy3.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        alergy3.setForeground(new java.awt.Color(0, 51, 153));
        alergy3.setText("Alergy 3 :");

        RecordNo.setEditable(false);
        RecordNo.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N

        Alergy1.setEditable(false);
        Alergy1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N

        Alergy2.setEditable(false);
        Alergy2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N

        Alergy3.setEditable(false);
        Alergy3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Alergy3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alergy3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(savingslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(routingno, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RoutingNo, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(accountno)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AccountNo))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Balance))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(accounttype, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AccountType))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bankname, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BankName, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 320, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(savingslabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(alergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Alergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(alergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Alergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(alergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Alergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(routingno1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(bankname1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(accountno1)
                                                .addComponent(balance1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(accounttype1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(AccountType1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                                            .addComponent(Balance1)
                                            .addComponent(RoutingNo1)
                                            .addComponent(BankName1)
                                            .addComponent(AccountNo1)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(recordno, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(RecordNo, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(medrec, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bloodtype, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expirydate, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ed, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lno, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(issuedate, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(licenseno)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(662, 662, 662)
                        .addComponent(DemoHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(piclabel, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(streetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(StreetAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                                    .addComponent(SSN)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(phoneno)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DoB, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(weight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(height, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                        .addComponent(city, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Wtg, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                                    .addComponent(Htg)
                                    .addComponent(Lname)
                                    .addComponent(City)
                                    .addComponent(ZipCode))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DemoHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneno)
                            .addComponent(age)
                            .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Htg, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SSN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Wtg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(streetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StreetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(City))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(zipcode)
                                    .addComponent(ZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)
                        .addComponent(savingslabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(piclabel, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(savingslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(accountno, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(balance)
                                .addComponent(Balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(accounttype)
                                .addComponent(AccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(6, 6, 6))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bankname)
                                .addComponent(BankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(routingno, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RoutingNo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(AccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(134, 134, 134)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BankName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bankname1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RoutingNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(routingno1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(accountno1)
                            .addComponent(AccountNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Balance1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(balance1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccountType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accounttype1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lno, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(licenseno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(issuedate, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(expirydate, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bloodtype, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(medrec, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RecordNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recordno, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alergy1)
                            .addComponent(Alergy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Alergy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Alergy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoBActionPerformed

    private void ZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZipCodeActionPerformed

    private void FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameActionPerformed
        // TODO add your handling code here:
              

    }//GEN-LAST:event_FnameActionPerformed

    private void CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityActionPerformed

    private void BalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BalanceActionPerformed

    private void AccountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountTypeActionPerformed

    private void Balance1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Balance1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Balance1ActionPerformed

    private void AccountType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountType1ActionPerformed

    private void btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btActionPerformed

    private void Alergy3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alergy3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Alergy3ActionPerformed

    private void StreetAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StreetAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StreetAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccountNo;
    private javax.swing.JTextField AccountNo1;
    private javax.swing.JTextField AccountType;
    private javax.swing.JTextField AccountType1;
    private javax.swing.JTextField Age;
    private javax.swing.JTextField Alergy1;
    private javax.swing.JTextField Alergy2;
    private javax.swing.JTextField Alergy3;
    private javax.swing.JTextField Balance;
    private javax.swing.JTextField Balance1;
    private javax.swing.JTextField BankName;
    private javax.swing.JTextField BankName1;
    private javax.swing.JTextField City;
    private javax.swing.JLabel DemoHeading;
    private javax.swing.JTextField DoB;
    private javax.swing.JTextField Fname;
    private javax.swing.JTextField Htg;
    private javax.swing.JTextField Lname;
    private javax.swing.JTextField Phoneno;
    private javax.swing.JTextField RecordNo;
    private javax.swing.JTextField RoutingNo;
    private javax.swing.JTextField RoutingNo1;
    private javax.swing.JTextField SSN;
    private javax.swing.JTextField State;
    private javax.swing.JTextField StreetAdd;
    private javax.swing.JTextField Wtg;
    private javax.swing.JTextField ZipCode;
    private javax.swing.JLabel accountno;
    private javax.swing.JLabel accountno1;
    private javax.swing.JLabel accounttype;
    private javax.swing.JLabel accounttype1;
    private javax.swing.JLabel age;
    private javax.swing.JLabel alergy1;
    private javax.swing.JLabel alergy2;
    private javax.swing.JLabel alergy3;
    private javax.swing.JLabel balance;
    private javax.swing.JLabel balance1;
    private javax.swing.JLabel bankname;
    private javax.swing.JLabel bankname1;
    private javax.swing.JLabel bloodtype;
    private javax.swing.JTextField bt;
    private javax.swing.JLabel city;
    private javax.swing.JLabel dob;
    private javax.swing.JTextField ed;
    private javax.swing.JLabel expirydate;
    private javax.swing.JLabel fname;
    private javax.swing.JLabel height;
    private javax.swing.JTextField id;
    private javax.swing.JLabel issuedate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField licenseno;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel lno;
    private javax.swing.JLabel medrec;
    private javax.swing.JLabel phoneno;
    private javax.swing.JLabel piclabel;
    private javax.swing.JLabel recordno;
    private javax.swing.JLabel routingno;
    private javax.swing.JLabel routingno1;
    private javax.swing.JLabel savingslabel;
    private javax.swing.JLabel savingslabel1;
    private javax.swing.JLabel ssn;
    private javax.swing.JLabel state;
    private javax.swing.JLabel streetAdd;
    private javax.swing.JLabel weight;
    private javax.swing.JLabel zipcode;
    // End of variables declaration//GEN-END:variables
}
