/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Airliners;

import Business.Flightdetails;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sharw
 */
public class ViewAirlinerDetails extends javax.swing.JPanel {

    /**
     * Creates new form ViewAirlinerDetails
     */
    
JPanel rightpane;
Flightdetails fd;
    ViewAirlinerDetails(JPanel rightpane, Flightdetails fd) {
        initComponents();
        this.rightpane=rightpane;
        this.fd=fd;
        
        display();
        //notxt.setText(convertInteger(fd.getFlightnumber()));
        //sourcetxt.setText(fd.getSource());
        //desttxt.setText(fd.getDestination());
        //seattxt.setText(convertInteger(fd.getSeats()));
        //datetxt.setText(fd.getDate());
        //pricetxt.setText(convertInteger(fd.getPrice()));
        
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void display(){
        notxt.setText(String.valueOf(fd.getFlightnumber()));
        sourcetxt.setText(fd.getSource());
        desttxt.setText(fd.getDestination());
        seattxt.setText(String.valueOf(fd.getSeats()));
        datetxt.setText(fd.getDate());
        pricetxt.setText(String.valueOf(fd.getPrice()));
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fnolabel = new javax.swing.JLabel();
        sourcelabel = new javax.swing.JLabel();
        destlabel = new javax.swing.JLabel();
        seatlabel = new javax.swing.JLabel();
        datelabel = new javax.swing.JLabel();
        pricelabel = new javax.swing.JLabel();
        pricetxt = new javax.swing.JTextField();
        datetxt = new javax.swing.JTextField();
        seattxt = new javax.swing.JTextField();
        desttxt = new javax.swing.JTextField();
        sourcetxt = new javax.swing.JTextField();
        notxt = new javax.swing.JTextField();
        uploadbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        fnolabel.setFont(new java.awt.Font("SansSerif", 1, 34)); // NOI18N
        fnolabel.setText("Flight Number:");

        sourcelabel.setFont(new java.awt.Font("SansSerif", 1, 34)); // NOI18N
        sourcelabel.setText("Source:");

        destlabel.setFont(new java.awt.Font("SansSerif", 1, 34)); // NOI18N
        destlabel.setText("Destination:");

        seatlabel.setFont(new java.awt.Font("SansSerif", 1, 34)); // NOI18N
        seatlabel.setText("Seats:");

        datelabel.setFont(new java.awt.Font("SansSerif", 1, 34)); // NOI18N
        datelabel.setText("Date:");

        pricelabel.setFont(new java.awt.Font("SansSerif", 1, 34)); // NOI18N
        pricelabel.setText("Price:");

        pricetxt.setEditable(false);
        pricetxt.setBackground(new java.awt.Color(255, 255, 255));
        pricetxt.setFont(new java.awt.Font("SansSerif", 0, 34)); // NOI18N
        pricetxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        datetxt.setEditable(false);
        datetxt.setBackground(new java.awt.Color(255, 255, 255));
        datetxt.setFont(new java.awt.Font("SansSerif", 0, 34)); // NOI18N
        datetxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        seattxt.setEditable(false);
        seattxt.setBackground(new java.awt.Color(255, 255, 255));
        seattxt.setFont(new java.awt.Font("SansSerif", 0, 34)); // NOI18N
        seattxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        desttxt.setEditable(false);
        desttxt.setBackground(new java.awt.Color(255, 255, 255));
        desttxt.setFont(new java.awt.Font("SansSerif", 0, 34)); // NOI18N
        desttxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        sourcetxt.setEditable(false);
        sourcetxt.setBackground(new java.awt.Color(255, 255, 255));
        sourcetxt.setFont(new java.awt.Font("SansSerif", 0, 34)); // NOI18N
        sourcetxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        notxt.setEditable(false);
        notxt.setBackground(new java.awt.Color(255, 255, 255));
        notxt.setFont(new java.awt.Font("SansSerif", 0, 34)); // NOI18N
        notxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));

        uploadbtn.setFont(new java.awt.Font("SansSerif", 1, 34)); // NOI18N
        uploadbtn.setText("Update");
        uploadbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));
        uploadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadbtnActionPerformed(evt);
            }
        });

        backbtn.setFont(new java.awt.Font("SansSerif", 1, 34)); // NOI18N
        backbtn.setText("<<Back");
        backbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        savebtn.setFont(new java.awt.Font("SansSerif", 1, 34)); // NOI18N
        savebtn.setText("Save");
        savebtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(153, 255, 255)));
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 39)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Airliner Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(465, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pricelabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datelabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sourcelabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnolabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sourcetxt)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uploadbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(desttxt)
                    .addComponent(seattxt)
                    .addComponent(datetxt)
                    .addComponent(pricetxt)
                    .addComponent(notxt))
                .addGap(396, 396, 396))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notxt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sourcelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sourcetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seattxt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pricelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pricetxt, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uploadbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void uploadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadbtnActionPerformed
        // TODO add your handling code here:
        notxt.setEditable(true);
        sourcetxt.setEditable(true);
        desttxt.setEditable(true);
        seattxt.setEditable(true);
        datetxt.setEditable(true);
        pricetxt.setEditable(true);
    }//GEN-LAST:event_uploadbtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        
        String no= notxt.getText().trim();
        String src=sourcetxt.getText().trim();
        String dest=desttxt.getText().trim();
        int s= Integer.parseInt(seattxt.getText().trim());
        String d=datetxt.getText().trim();
        int p=Integer.parseInt(pricetxt.getText().trim());
        
        fd.setFlightnumber(no);
        fd.setSource(src);
        fd.setDestination(dest);
        fd.setSeats(s);
        fd.setDate(d);
        fd.setPrice(p);
        JOptionPane.showMessageDialog(null, "updated successfully");
        
        notxt.setEditable(false);
        sourcetxt.setEditable(false);
        desttxt.setEditable(false);
        seattxt.setEditable(false);
        datetxt.setEditable(false);
        pricetxt.setEditable(false);
        
    }//GEN-LAST:event_savebtnActionPerformed

    private void backAction() {
        rightpane.remove(this);
        Component[] componentArray = rightpane.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AirlinerTableDetails atd = (AirlinerTableDetails) component;
        atd.populate1();
        CardLayout layout = (CardLayout) rightpane.getLayout();
        layout.previous(rightpane);
    }
    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        backAction();
    }//GEN-LAST:event_backbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel datelabel;
    private javax.swing.JTextField datetxt;
    private javax.swing.JLabel destlabel;
    private javax.swing.JTextField desttxt;
    private javax.swing.JLabel fnolabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField notxt;
    private javax.swing.JLabel pricelabel;
    private javax.swing.JTextField pricetxt;
    private javax.swing.JButton savebtn;
    private javax.swing.JLabel seatlabel;
    private javax.swing.JTextField seattxt;
    private javax.swing.JLabel sourcelabel;
    private javax.swing.JTextField sourcetxt;
    private javax.swing.JButton uploadbtn;
    // End of variables declaration//GEN-END:variables
}
